---
title: "Untitled"
output: html_document
date: "2026-02-26"
---

```{r}
library(tidyverse)
library(readr)

or_multivariable <- function(status, variable, confounders, data) {
    # formulation
    form <- as.formula(
        paste(
            status, "~", variable, "+",
            paste(all.vars(confounders), collapse = " + ")
        )
    )

    model <- glm(
        form,
        family = binomial(link = "logit"),
        data = data
    )

    beta <- coef(model)[[variable]]
    OR <- exp(beta)

    return(OR)
}
```


```{r}
args <- commandArgs(trailingOnly = TRUE)
prs_score_file <- args[1]
trait_file <- args[2]
output_file <- args[3]

cat("Processing PRS: ", prs_score_file, "\n")

trait_df <- read_csv(trait_file)

covars <- c("person_id", "age_2025", "sex_at_birth", paste0("PC", 1:10))
all_trait <- setdiff(colnames(trait_df), covars)

prs_score_df <- read_csv(prs_score_file) %>%
    select(IID, SUM) %>%
    rename(person_id = IID, score = SUM)

# merge trait + covariates + score
df <- trait_df %>%
    inner_join(prs_score_df, by = "person_id")

results <- list()
pc_terms <- paste0("PC", 1:10, collapse = " + ")
conf_formula <- as.formula(paste("~ age_2025 + sex_at_birth +", pc_terms))
for (trait in all_trait) {
    cat("  Trait: ", trait)

    res <- or_multivariable(
        status = trait,
        variable = "score",
        confounders = conf_formula,
        data = df
    )

    results[[length(results) + 1]] <- data.frame(
        trait = trait,
        OR = res
    )
}

final_df <- bind_rows(results)
write_csv(final_df, output_file)
```

```{r}
or_binary <- function(status, variable, confounders, data) {
    # covarate model
    data$Atmp <- data[[variable]]
    form_exp <- update.formula(confounders, Atmp ~ .)

    model_exp <- glm(form_exp,
        family = binomial(link = "logit"),
        data = data
    )

    pA <- predict(model_exp, type = "response")

    # IPW weight
    A <- data[[variable]]
    pA_marginal <- mean(A)
    weights_ipw <- ifelse(A == 1, pA_marginal / pA, (1 - pA_marginal) / (1 - pA))

    q_low <- quantile(weights_ipw, 0.01)
    q_high <- quantile(weights_ipw, 0.99)
    weights_ipw <- pmin(pmax(weights_ipw, q_low), q_high)

    model_ipw <- glm(
        as.formula(paste(status, "~", variable)),
        weights = weights_ipw,
        family = binomial(link = "logit"),
        data = data
    )

    beta <- coef(model_ipw)[variable]
    OR <- exp(beta)

    return(OR)
}
```



```{r cars}
args <- commandArgs(trailingOnly = TRUE)
prs_score_file <- args[1]
trait_file <- args[2]
output_file <- args[3]

cat("Processing PRS: ", prs_score_file, "\n")

trait_df <- read_csv(trait_file)

covars <- c("person_id", "age_2025", "sex_at_birth", paste0("PC", 1:10))
all_trait <- setdiff(colnames(trait_df), covars)

prs_score_df <- read_csv(prs_score_file) %>%
    select(IID, SUM) %>%
    rename(person_id = IID, score = SUM)

results <- list()
pc_terms <- paste0("PC", 1:10, collapse = " + ")
conf_formula <- as.formula(paste("~ age_2025 + sex_at_birth +", pc_terms))

# merge trait + covariates + score
df <- trait_df %>%
    inner_join(prs_score_df, by = "person_id")

results <- list()

for (trait in all_trait) {
    cat("  Trait: ", trait)

    res <- or_binary(
        status = trait,
        variable = "score",
        confounders = conf_formula,
        data = df
    )

    results[[length(results) + 1]] <- data.frame(
        trait = trait,
        adjauc = as.numeric(res)
    )
}

final_df <- bind_rows(results)
write_csv(final_df, output_file)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
